config/routes.rb
Rails.application.routes.draw do
  get "/meetingdates/new" => "meeting_dates#new"
  post  "/meetingdates/show" => "meeting_dates#create"
  resources :meeting_dates
  resources :users

  
  root 'time#show'

end

app/models/meeting_date.rb
class MeetingDate < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meeting_dates_controller.rb
class MeetingDatesController < ApplicationController

	  def index
  	    @meeting_dates = MeetingDate.all
      end

	  def new
	    @meeting_date = MeetingDate.new
	  end

	  def create
	    @meeting_date = MeetingDate.new(meeting_date_params)
	    
	    @meeting_date.save
	    redirect_to @meeting_date
	  end

	  def show
	  	@meeting_date = MeetingDate.find(params[:id])
	  end

	  def destroy
	    @meeting_date = MeetingDate.find(params[:id])
	    @meeting_date.destroy

	    redirect_to meetingdates_path
	  end
	  
	  private

	    def meeting_date_params
	      params.require(:meeting_date).permit(:date, :book)
	    end

end

app/controllers/time_controller.rb
class TimeController < ApplicationController
	def show 
	end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    @user.save
    redirect_to @user
  end

  def show
  	@user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end
  
  private

    def user_params
      params.require(:user).permit(:username, :email)
    end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/time_helper.rb
module TimeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300,100' rel='stylesheet' type='text/css'>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/meeting_dates/index.html.erb
<h1>Pick a date</h1>

<table>
    <thead>
        <th>Date</th>
        <th>Book</th>
    </thead>
    <tbody>
     <% @meeting_dates.each do |meeting| %>
      <tr>
        <td><%= meeting.date %></td>
        <td><%= meeting.book %></td>
      </tr>
     <% end %>
    </tbody>
</table>

app/views/meeting_dates/new.html.erb
<head>
    <meta charset="utf-8">
    <title>jQuery UI Datepicker - Default functionality</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css">	
    <script>
       $(function() {
           $( "#datepicker" ).datepicker();
       });
    </script>
</head>
<body>
 
  
	<h1>Pick a set of dates</h1>
	
	<div class="userlist">
	<%= form_for @meeting_date do |f| %> 
	    <%= f.label "option 1" %>
	    <%= f.date_field :date %>
	    
	    <%= f.label :book %>
	    <%= f.text_field :book %>
	    <%= f.submit "Create", :class => "button", :id => "special" %>
	</div>
	    
	<% end %>

	<form>
	  <div class="row">
	    <div class="large-12 columns">
	      <label>Input Label
	        <input type="text" placeholder="large-12.columns" />
	      </label>
	    </div>
	  </div>
	  <div class="row">
	    <div class="large-4 columns">
	      <label>Input Label
	        <input type="text" placeholder="large-4.columns" />
	      </label>
	    </div>
	    <div class="large-4 columns">
	      <label>Input Label
	        <input type="text" placeholder="large-4.columns" />
	      </label>
	    </div>
	    <div class="large-4 columns">
	      <div class="row collapse">
	        <label>Input Label</label>
	        <div class="small-9 columns">
	          <input type="text" placeholder="small-9.columns" />
	        </div>
	      </div>
	    </div>
	  </div>
	  <div class="row">
	    <div class="large-12 columns">
	      <label>Select Box
	        <select>
	          <option value="husker">Husker</option>
	          <option value="starbuck">Starbuck</option>
	          <option value="hotdog">Hot Dog</option>
	          <option value="apollo">Apollo</option>
	        </select>
	      </label>
	    </div>
	  </div>
	  <div class="row">
	    <div class="large-6 columns">
	      <label>Choose Your Favorite</label>
	      <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Red</label>
	      <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Blue</label>
	    </div>
	    <div class="large-6 columns">
	      <label>Check these out</label>
	      <input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label>
	      <input id="checkbox2" type="checkbox"><label for="checkbox2">Checkbox 2</label>
	    </div>
	  </div>
	  <div class="row">
	    <div class="large-12 columns">
	      <label>Textarea Label
	        <textarea placeholder="small-12.columns"></textarea>
	      </label>
	    </div>
	  </div>
	</form>
</body> 

app/views/meeting_dates/show.html.erb
<body>
	<table>
	  <thead>
	    <tr>
	      <th width="200">Dates</th>
	      <th width="150">Book</th>
	    </tr>
	  </thead>
	  <tbody>
	    <tr>
	      <td><%= @meeting_date.date %></td>
	      <td><%= @meeting_date.book %></td>
	    </tr>
	  </tbody>
	</table>
	<%= link_to "See All", meeting_dates_path, :class => "button" %>
</body> 

app/views/time/show.html.erb
  <div>
	<%= link_to "Create a new user", new_user_path, :class => "button", :id => "padded" %>
  </div> 
  
  <div class="more_space">
	<%= link_to "Pick Date", meetingdates_new_path, :class => "button" %>
  </div>

app/views/users/index.html.erb
<h1>The People</h1>

<table>
    <thead>
        <th>Name</th>
        <th>Email</th>
    </thead>
    <tbody>
     <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user_path(user), :class => "label" %></td> 
        <td><%= link_to 'Destroy', user_path(user),
              method: :delete, :class => "label",
              data: { confirm: 'Are you sure?' } %></td> 
      </tr>
     <% end %>
    </tbody>
</table>

 <%= link_to "Be somebody", new_user_path, :class => "button" %>

app/views/users/new.html.erb
<body data-no-turbolink="true">
<h1>Make someone new</h1>

<div class="userlist">
<%= form_for(@user) do |f| %> 
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.submit "Create", :class => "button", :id => "special" %>
</div>
    
<% end %>
<body> 

app/views/users/show.html.erb
<body>
	<table>
	  <thead>
	    <tr>
	      <th width="200">Name</th>
	      <th width="150">Email</th>
	    </tr>
	  </thead>
	  <tbody>
	    <tr>
	      <td><%= @user.username %></td>
	      <td><%= @user.email %></td>
	    </tr>
	  </tbody>
	</table>
	<%= link_to "See All", users_path, :class => "button" %>
</body> 